name: Unzip File

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Unzip file to root
        run: unzip -o LaTunisieMedicaleIndexer-fixed.zip -d .
